const products = [
  {
    imgSrc: require("../../assets/images/suggestion/product1.jpg"),
    islike: true,
    sale: 43,
    freeShip: true,
    desc: "Quần short nữ ống rộng lưng cao cạp thun chun có túi in phồng hoa nổi - Quần đùi nữ mặc ở nhà đi ngủ thể thao đi biển",
    discountCode: "",
    price: 46000,
    sold: 4023,
  },
  {
    imgSrc: require("../../assets/images/suggestion/product2.jpg"),
    islike: true,
    sale: 36,
    freeShip: false,
    desc: "Combo bộ rổ nhựa vuông 6 món kèm chậu ráo nước hai lớp cao cấp tiện lợi",
    discountCode: "",
    price: 9000,
    sold: 2913,
  },
  {
    imgSrc: require("../../assets/images/suggestion/product3.jpg"),
    islike: true,
    sale: 50,
    freeShip: true,
    desc: "[Mã FAWEEKDAY2 giảm 10K đơn 50K] Quần jogger nữ bigsize ống rộng cotton thoải mái không xù Bigzone",
    discountCode: "",
    price: 75000,
    sold: 1932,
  },
  {
    imgSrc: require("../../assets/images/suggestion/product4.jpg"),
    islike: true,
    sale: 4,
    freeShip: true,
    desc: "Mắt kính unisex hot trend thời trang 💖FREESHIP💖 gọng kính mát nam nữ nhiều màu phong cách",
    discountCode: "",
    price: 24000,
    sold: 63343,
  },
  {
    imgSrc: require("../../assets/images/suggestion/product5.jpg"),
    islike: true,
    sale: 46,
    freeShip: true,
    desc: "[Mã FAWEEKDAY2 giảm 10K đơn 50K] Áo Thun Nam Nữ Form Rộng CALIFORNIA Cotton Unisex 2 Màu Ulzzang ATN22",
    discountCode: "",
    price: 60000,
    sold: 337,
  },
  {
    imgSrc: require("../../assets/images/suggestion/product6.jpg"),
    islike: false,
    sale: 50,
    freeShip: true,
    desc: "Đồng Hồ Điện Tử Dây Silicone Thể Thao Cho Học Sinh",
    discountCode: "10%",
    price: 25575,
    sold: 799,
  },
];

export { products };
